### PR TITLE
add/update/replace submodules

### PR DESCRIPTION
**Pull request by opadron**
- add submodule: gobig
  - add devops resources
- update submodules
  - girder
  - github-site
  - osumo
- replace submodule: romanesco -> girder_worker

### CODE REVIEW

**Comment by opadron** [comment]
@osumo PTAL.  I could have sworn we had merged this in already?

**Comment by opadron** [comment]
Pinging @osumo/developers (not sure if the above ping works).

**Comment by jeffbaumes** [comment]
The updates LGTM at surface level so I'm ok for you to merge. For the future is there an easy way to test out this provisioning?

**Comment by opadron** [comment]
@jeffbaumes see [this](https://github.com/Kitware/gobig/pull/38#issuecomment-158142660) discussion for the last time testing provisioning resources were brought up.  Basically, we can do it, but will need dedicated AWS instances + some high-availability system that we control to trigger the extended testing process.  Lightweight CI services like Travis would not be enough for this kind of testing.

**Comment by jeffbaumes** [comment]
@opadron I was more asking for a README.md on this repo that tells people how to use it (even if we don't have automated testing), so that people like me can manually try out PRs like this one.

**Comment by opadron** [comment]
I see what you're saying.  I'll see about throwing together a quick README.  Basically, there are convenience scripts for setting up a virtualenv and running a mongodb instance, but the process boils down to checking out the repo and running girder with the osumo plugin and girder-worker (at the versions pegged in the submodules).

**Pull request merged**
