### PR TITLE
submodule updates

### PR DESCRIPTION
**Pull request by opadron**
- girder
- girder_worker
- osumo

### CODE REVIEW

**Comment by opadron** [comment]
Staging Environment [here](http://52.86.100.86)

One thing I've noticed is that the worker will randomly bail with some error about an invalid cross-device link.

@manthey @ronichoudhury any ideas?

**Comment by waxlamp** [comment]
Can you document the exact error message here please?

**Comment by opadron** [comment]
This is after my feeble attempt to reformat:

```
ERROR - 2016-08-01T15:38:48.082000+00:00
  - <type 'exceptions.OSError'>:
  [Errno 18] Invalid cross-device link

    File "/opt/osumo-project/girder_worker/girder_worker/__main__.py", line 33,
      in run retval = girder_worker.run(*pargs, **kwargs)
    File "girder_worker/utils.py", line 306,
      in wrapped return fn(*args, **kwargs)
    File "girder_worker/__init__.py", line 277,
      in run d, **dict({'task_input': task_input}, **kwargs))
    File "girder_worker/io/__init__.py", line 132,
      in fetch return _fetch_map[mode](spec, **kwargs)
    File "/opt/osumo-project/girder_worker/girder_worker/plugins/girder_io/__init__.py", line 95,
      in fetch_handler client.downloadFile(spec['id'], dest)
    File "/opt/osumo-project/cache/env/local/lib/python2.7/site-packages/girder_client/__init__.py", line 934,
      in downloadFile os.rename(tmp.name, path)
```

You can try it yourself [here](http://52.86.100.86/#process).  Just keep running jobs and you should see the same error.

**Comment by waxlamp** [comment]
Found this: http://stackoverflow.com/questions/11578443/trigger-io-errno-18-cross-device-link

It seems to be something about how `os.rename()` works, perhaps the fact that it uses hard links to safely move the file (another Google result mentions hard links in connection to this error message).

Here's something about `os.rename()` vs. `shutil.move()` (but it is a rather old message, so _caveat emptor_): https://mail.python.org/pipermail/tutor/2011-April/083076.html

**Comment by opadron** [comment]
Looks like it's an issue in girder.  Though, I wonder why it doesn't happen every time.

**Comment by opadron** [comment]
Actually, I just noticed something pretty important: it seems like running jobs on staging consistently fails every _other_ job.

**Comment by waxlamp** [comment]
I guess this has to do with the way hard links work across different mount points or something. I guess we should file an issue report with Girder?

**Comment by opadron** [comment]
Alright! Looks like it's working now! http://52.86.100.86#process
@osumo/developers PTAL, and make sure everything works for you.

**Comment by manthey** [comment]
LGTM

**Pull request merged**
